apiVersion: v1
kind: Secret
metadata:
  name: postgres-credentials
  namespace: apps
type: Opaque
stringData:
  POSTGRES_USER: postgres
  POSTGRES_PASSWORD: f0LKn9Dnm7n3bubQciV8ZIMjVPQ0mFnn
  POSTGRES_DB: app
