apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

# Point the image tag at your Artifact Registry image.
# Update newTag after each docker build/push.
images:
  - name: devbox
    newName: us-central1-docker.pkg.dev/bens-project-462804/devbox/devbox
    newTag: latest
